### ISSUE TITLE
源码就放在这儿吧，也懒得git了~

### ISSUE THREAD

**Issue by altCoinDiscuss** [altCoinDiscuss/coinMonitor#1]
#监控各区块链项目twitter情况
#pycharm
import tweepy
import time
import smtplib
from email import encoders
from email.header import Header
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.utils import parseaddr, formataddr
from email.mime.application import MIMEApplication

##########推特登录###########
consumer_key = '自行输入'
consumer_secret = '自行输入'
access_token = '自行输入'
access_token_secret = '自行输入'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

time_now = time.strftime("%Y-%m-%d-%H:%M:%S", time.localtime())
file_name = "data/" + time_now + ".txt"
txt_file = open(file_name,'w')

for name in open("name.txt"):
    user = api.get_user(name)
    txt_file.write(str(user.followers_count))
    txt_file.write('\n')
txt_file.close()

#################################
#############邮件发送##############
#################################
from_addr = '自行输入@qq.com'
mail_key = '自行输入'
to_addr = '自行输入@qq.com'
smtp_server = 'smtp.qq.com'

msg = MIMEMultipart()
msg.attach(MIMEText('当前各项目推特关注数', 'plain', 'utf-8'))
msg['From'] = from_addr
msg['To'] = to_addr
msg['Subject'] = Header('当前各项目twitter用户数追踪','utf-8').encode()

###################附件添加#########
email_file = MIMEApplication(open(file_name, 'rb').read())
email_file.add_header('Content-Disposition', 'attachment', filename=file_name)
msg.attach(email_file)

server = smtplib.SMTP(smtp_server, 25)
server.set_debuglevel(1)
server.login(from_addr,mail_key)
server.sendmail(from_addr,to_addr,msg.as_string())
server.quit()#退出邮箱服务器

**Comment by royalrover** [comment]
name.txt 这个文件没放出来

**Comment by altCoinDiscuss** [comment]
@royalrover name.txt里面，每一行就是一个twitter的name。

**Comment by popboykingdjko** [comment]
> name.txt 这个文件没放出来

能分享一下推特开发者账号吗？

**Comment by altCoinDiscuss** [comment]
> > name.txt 这个文件没放出来
> 
> 能分享一下推特开发者账号吗？

这个账号自己申请就行了，网上教程很多，国内申请相对麻烦，但是+86和gmail时可以申请下来的。我就是。

**Comment by popboykingdjko** [comment]
> 申请

我没有申请下来，申请了，老哥，如果方便，能不能加个微信好友，一起研究研究怎么通过程序更好的进行炒币，你看行吗？

**Comment by altCoinDiscuss** [comment]
> > 申请
> 
> 我没有申请下来，申请了，老哥，如果方便，能不能加个微信好友，一起研究研究怎么通过程序更好的进行炒币，你看行吗？

如果你炒币经验比较丰富的话，可以，麻烦留一下微信，我加你

**Comment by altCoinDiscuss** [comment]
> > 申请
> 
> 我没有申请下来，申请了，老哥，如果方便，能不能加个微信好友，一起研究研究怎么通过程序更好的进行炒币，你看行吗？

**Comment by highertq** [comment]
今天刚看到，和我的思路是一样的，老哥稳。

**Comment by altCoinDiscuss** [comment]
> 今天刚看到，和我的思路是一样的，老哥稳。

信息有很多，关键在于筛选

**Comment by zqwuming** [comment]
主要在币安 使用aioquant框架交易 加个微信交流好不 zqwuming

**Comment by Du1406610194** [comment]
大佬加个微信 1406610194

**Comment by jianghao233** [comment]
老哥拉个微信群呗 微信：jh1419157874,求拉！！！

**Comment by 6EGG6** [comment]
> @royalrover name.txt里面，每一行就是一个twitter的name。

2490458838求求你求求你

**Comment by pom336699** [comment]
15653646014大佬加我一下

**Comment by kuangxiaogou** [comment]
15803814763，大佬加我一下

**Comment by zqwuming** [comment]
大佬 通过下，名字是草原

发送自 Windows 10 版邮件应用

发件人: Du
发送时间: 2021年7月10日 6:34
收件人: altCoinDiscuss/coinMonitor
抄送: zqwuming; Manual
主题: Re: [altCoinDiscuss/coinMonitor] 源码就放在这儿吧，也懒得git了~ (#1)

大佬加个微信 1406610194

**Comment by kklam2** [comment]
可以加个微信一起交流吗？183495735

**Comment by cainiaoyigao** [comment]
15768135753？

**Comment by POPPOOI** [comment]
18817669568，大佬可以交流下吗
