### ISSUE TITLE
国外区块链纪实

### ISSUE THREAD

**Issue by altCoinDiscuss** [altCoinDiscuss/coinMonitor#2]
SHA256:
19a80290d4de8a8d36dd69dfa22661503f4b928df446c62e2cc68ebbf500d8db

**Comment by highertq** [comment]
这又是啥

**Comment by altCoinDiscuss** [comment]
这个项目追踪一个新区块链token，token_address的SHA256值，如上。
该项目团队为国外团队，操盘方式还未传入国内，属于短期会暴涨项目。
本人将实时参与该项目，后续公布盈利，并公布该项目操盘方式。

**Comment by highertq** [comment]
带带弟弟，冲，tg多少？

**Comment by altCoinDiscuss** [comment]
短期韭菜局，非价值投资，不带任何人冲。

**Comment by highertq** [comment]
我没钱冲 穷逼一个 给大佬端茶倒水干点零碎活罢了

**Comment by AngusLean** [comment]
老哥，SHA256没法查出对应的项目啊-- 
有其他提示么，我自己瞅瞅

**Comment by altCoinDiscuss** [comment]
该项目为小众公链solana项目，盈利手段为前期私募，私募后即跑路。注意风险。
